### ISSUE TITLE
if Notification use When and Id = 1, then app will crash

### ISSUE THREAD

**Issue by SyaoranChang** [aritchie/notifications#41]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [X] .NET Standard

## Version of OS(s) listed above with issue
Android 7.1.0

## Version of Library
Acr.Notifications 4.0.0

## Actual Behavior
            await CrossNotifications.Current.Send(new Notification
            {
                Title = "HELLO!",
                Message = "Hello from the ACR Sample Notification App",
                Vibrate = true,
                When = TimeSpan.FromSeconds(10),
                Id = 1
            });

if use When and Id = 1, then app will crash.
id > 1 (e.g. id = 2, id = 1000) then show Notifications and app run normal.

crash log
Unhandled Exception:
SQLite.SQLiteException: Constraint

**Comment by aritchie** [comment]
Please include the entire stack trace in the future.  I can already guess what the issue is though.  You are likely creating multiple notifications with the same ID which you cannot do.

You have two choices, 1) you manage the ID and make sure it is unique per notifications OR 2) let the library manage the ID (meaning, you don't set it)
