### ISSUE TITLE
Not compatible with Xamarin.Android.Support.v4 26.1.0.1

### ISSUE THREAD

**Issue by Kilowhisky** [aritchie/notifications#48]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] UWP
 - [] .NET Standard

## Version of Library
4.0.2

## Actual Behavior
I can't upgrade xamarin packages because it says this plugin is limiting supported versions.

```
Unable to resolve dependencies. 'Xamarin.Android.Support.v4 26.1.0.1' is not compatible with 'Plugin.Notifications 4.0.2 constraint: Xamarin.Android.Support.v4 (>= 25.3.1 && < 26.0.0)'.
```

**Comment by erhan0** [comment]
I have this exact same problem. Is there a way to loosen the Plugin.Notifications constraint to allow 26.0.0 and above?

**Comment by EmilAlipiev** [comment]
so is it advised to use pre release if I am on support libraries 27? how stable is the pre release? :)

**Comment by jordan-hewitt** [comment]
Bump, did anyone find a workaround?  I really do not want to have to revert my android packages to older versions to get this to work.

**Comment by she2** [comment]
@jordan-hewitt I used https://www.nuget.org/packages/Plugin.Notifications/5.0.0-beta3. The issue was resolved.

**Comment by polystyreneMan** [comment]
Is anyone else getting the following error on 5.0.0-beta3 to your Android project? I'm trying to use it for the same reason as you guys, but it won't install:

_Failed to add reference. The package 'Plugin.Notifications' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance._

I think betas 1 and 2 work on my Android project, but they don't work with my PCL because the .NET profile is not supported.

**Comment by aritchie** [comment]
I don't support PCL any longer.  Also, this defect is being closed since I don't take requests for support library bumps.  Use the beta... I will be doing a release in the near future.
