### ISSUE TITLE
second activity from notification

### ISSUE THREAD

**Issue by EmilAlipiev** [aritchie/notifications#5]
Is it possible to define a second activity when you tap the notification? I would like open a page from the notification but i couldn't figure out how to do it?

**Comment by aritchie** [comment]
No.  Probably never will be because it wouldn't be very cross platform.  Managing the incoming notification is done on the platform usually via one location and then forwarded appropriately.  I may allow context data to be shipped through the notification PCL to be read on the platform in the future.

If you are wondering what the library can do, PLEASE look at the source code.  I don't mind supporting bugs and feature requests, but you can answer your own questions when the library is this small.
