### ISSUE TITLE
Unfortynately, "my app name" has stopped on Android

### ISSUE THREAD

**Issue by acaliaro** [aritchie/notifications#6]
Hi @aritchie .
I have this problem using your library.
It exists only on Android (and not all version... I am trying 4.4.2 a Symbol Motorola TC700H but on other devices it does not appear).
The library works well (I am using 1.5.2). The problem appears when  I restart the handheld.
The message "Unfortunately XXX has stopped" appears.
The only way to have not this message at startup is to remove your Acr.Notifications packages from Android and Forms projects.
Have you a workaround for this?
Thanks
Alessandro

**Comment by acaliaro** [comment]
Sorry @aritchie... It appears on all android devices we have tested

**Comment by aritchie** [comment]
you have given me absolutely zero details as to the actual crash.  You have to supply proper details like a stack trace at the very least if you are hoping for any sort of help!

**Comment by acaliaro** [comment]
Thanks @aritchie . Can you tell me how can I send you a Trace. The problem appears when I restart the handheld without run the app. Exists an Android Stack? Sorry for the question...

**Comment by acaliaro** [comment]
Hi @aritchie . I think to have a log. I attach it. It's a log at device startup. GeoBadge is my app... at the end of the log, you can see "process died"

[log.txt](https://github.com/aritchie/notifications/files/243306/log.txt)

**Comment by acaliaro** [comment]
@aritchie I have this project that has the problem.
Can you take a look? Thanks

[altbeacon-forms-test.zip](https://github.com/aritchie/notifications/files/243548/altbeacon-forms-test.zip)

**Comment by aritchie** [comment]
@acaliaro I'm not debugging apps for you.  This isn't even a testcase, it is another app.  The fact is, I use this plugin in my apps without issue at the moment.  Your log file doesn't suggest any problem with the library, though I do see permission errors around location and you're using beacons.   

This library uses a bootcomplete event that starts up your app automatically so that scheduled notifications can run.  Try removing the plugin and creating your own your own broadcast receiver with an intent filter that runs on ActionBootCompleted.  If your code is still crashing, look elsewhere.  You can see an example of this in the android plugin as well as how to register it.

I will be happy to help with defects and feature requests around the library so long as they have proper information.

**Comment by EmilAlipiev** [comment]
@aritchie  reading your comment above. Do I understand correct that we need to enable "RECEIVE_BOOT_COMPLETED" in manifest in order to get scheduled notifications if app is not running?

**Comment by aritchie** [comment]
@EmilAlipiev please quit trolling closed issues!  I set the notifications on the alarm manager since v2, so you shouldn't need a receive_boot_completed any longer.
